export { default as Hero } from './Hero'
export { default as Features } from './Features'
export { default as Pricing } from './Pricing'
export { default as Contact } from './Contact'
export { default as About } from './About'